"""adicionando as colunas de controle de resumos dos chats

Revision ID: 0da8110560f2
Revises: 30ea24edb143
Create Date: 2025-07-10 22:05:59.279554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da8110560f2'
down_revision: Union[str, None] = '30ea24edb143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_chat', sa.Column('compacted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historico_chat', 'compacted')
    # ### end Alembic commands ###
