"""melhorando mais uma vez tabela de histórico de chats

Revision ID: 596a5724cb70
Revises: 94c3ab2efa60
Create Date: 2025-07-01 21:39:07.399219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '596a5724cb70'
down_revision: Union[str, None] = '94c3ab2efa60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_chat', sa.Column('titulo_chat', sa.String(length=255), nullable=True))
    op.add_column('historico_chat', sa.Column('prompt_description', sa.Text(), nullable=False))
    op.add_column('historico_chat', sa.Column('response_description', sa.Text(), nullable=True))
    op.drop_column('historico_chat', 'texto_chat')
    op.drop_column('historico_chat', 'mensagem_ia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_chat', sa.Column('mensagem_ia', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='coluna boolean para identificar se a mensagem é da IA'))
    op.add_column('historico_chat', sa.Column('texto_chat', mysql.TEXT(), nullable=False))
    op.drop_column('historico_chat', 'response_description')
    op.drop_column('historico_chat', 'prompt_description')
    op.drop_column('historico_chat', 'titulo_chat')
    # ### end Alembic commands ###
