"""melhorando tabela de histórico de chats

Revision ID: 94c3ab2efa60
Revises: a4f5633a86a6
Create Date: 2025-07-01 21:15:53.889470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94c3ab2efa60'
down_revision: Union[str, None] = 'a4f5633a86a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_chat', sa.Column('mensagem_ia', sa.Boolean(), nullable=False, comment='coluna boolean para identificar se a mensagem é da IA'))
    op.drop_column('historico_chat', 'origem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_chat', sa.Column('origem', mysql.VARCHAR(length=50), nullable=False, comment='Usuário ou IA'))
    op.drop_column('historico_chat', 'mensagem_ia')
    # ### end Alembic commands ###
