"""adicionando coluna ativo na tabela de agent_memory

Revision ID: aabf86a23a3c
Revises: d3ced4e1b0d7
Create Date: 2025-06-26 20:47:35.991999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabf86a23a3c'
down_revision: Union[str, None] = 'd3ced4e1b0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_memory', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_memory', 'ativo')
    # ### end Alembic commands ###
