"""guardando refresh token no banco

Revision ID: b57e7102a598
Revises: 9bb72d75ebb9
Create Date: 2025-05-19 22:53:11.004218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57e7102a598'
down_revision: Union[str, None] = '9bb72d75ebb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('refresh_token_exp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'refresh_token_exp')
    op.drop_column('usuarios', 'refresh_token')
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###
