"""acess_token na tabela de usuarios

Revision ID: ce0d888c72e7
Revises: b57e7102a598
Create Date: 2025-05-20 21:22:02.385015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0d888c72e7'
down_revision: Union[str, None] = 'b57e7102a598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('acess_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'acess_token')
    # ### end Alembic commands ###
